print("Things I know about you!")
print()

userName = input("What is your username?: ")
favFood = input("What is your favorite food?: ")
favMusic = input("What is your favorite music?: ")
favColor = input("What is your favorite color?: ")
favMovie = input("What is your favorite movie?: ")
favGame = input("What is your favorite game?: ")
location = input("What is your favorite destination?: ")

print() 
print("You are")
print(userName)
print("You enjoying eating ")
print(favFood)
print("while listening to ")
print(favMusic)
print("wearing a " + favColor + " polo and jeans. ")
print("You also enjoy watching ")
print(favMovie)
print("or the game of ")
print(favGame)
print("while on tour in " + location)

